Получить информацию обо всех книгах и сохранить в pd.DataFrame

In [4]:
import requests
import pandas as pd

In [81]:
api_base_url = 'https://www.anapioficeandfire.com/api/books/'

In [82]:
books = requests.get(api_base_url
).json()

In [83]:
df_books = pd.DataFrame(books)
df_books.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

Получить информацию обо всех домах Вестероса (Houses) и сохранить в pd.DataFrame

In [87]:
houses_url = 'https://www.anapioficeandfire.com/api/houses/'
filter = {'region':'The Westerlands'}
houses = requests.get(houses_url, filter
).json()
df_houses = pd.DataFrame(houses)
df_houses

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/20,House Bettley,The Westerlands,"Three blue beetles, on a gold field(Or, three ...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/40,House Brax of Hornvale,The Westerlands,"A purple unicorn, on a silver field(Argent, a ...",,[],[Hornvale],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/46,House Broom,The Westerlands,"A silver helm crested with a sprig of broom, o...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
5,https://www.anapioficeandfire.com/api/houses/62,House Casterly of Casterly Rock,The Westerlands,,,[Lord of Casterly Rock],[Casterly Rock],,,,Age of Heroes,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/...,[https://www.anapioficeandfire.com/api/charact...
6,https://www.anapioficeandfire.com/api/houses/72,House Clegane,The Westerlands,"Three dogs on a yellow field(Or, three dogs co...",,[Ser],[Clegane's Keep],,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
7,https://www.anapioficeandfire.com/api/houses/73,House Clifton,The Westerlands,,,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/120,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
8,https://www.anapioficeandfire.com/api/houses/86,House Crakehall of Crakehall,The Westerlands,"A brindled boar on a brown field(Tenné, a boar...",None so Fierce,[Lord of Crakehall],[Crakehall],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
9,https://www.anapioficeandfire.com/api/houses/101,House Doggett,The Westerlands,"Per bend, a white unicorn on a green field, a ...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]

Получить информацию обо всех домах Вестероса, у которых есть девиз, и сохранить в pd.DataFrame

In [88]:
houses_url = 'https://www.anapioficeandfire.com/api/houses/'
filter = {'region':'The Westerlands'}
houses = requests.get(houses_url, filter
).json()
df_houses = pd.DataFrame(houses)
df_houses = df_houses[df_houses['words']!='']
df_houses

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
8,https://www.anapioficeandfire.com/api/houses/86,House Crakehall of Crakehall,The Westerlands,"A brindled boar on a brown field(Tenné, a boar...",None so Fierce,[Lord of Crakehall],[Crakehall],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...

Работа с БД

In [1]:
import psycopg2

In [2]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

try:
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

In [5]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database limit 10')
    rnc_10 = cursor.fetchall()

rnc_df = pd.DataFrame(rnc_10)
rnc_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,21,2017-05-02,RNACEN,NONCODE,146,NONCODE,Y,,NONCODE,,1130.0,201.0,244296.0,234669,7,is an integrated knowledge database dedicated ...,http://www.noncode.org/,"[{'upi': 'URS000019B796', 'taxid': 9606}, {'up...",[{'title': 'NONCODE 2016: an informative and v...
1,5,2017-05-17,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,1,2017-05-01,RNACEN,ENA,968,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
4,14,2017-05-01,RNACEN,TAIR,982,TAIR,Y,,TAIR,PRJ_TAIR,384.0,19.0,6227.0,4406,1,is a database of genetic and molecular biology...,http://www.arabidopsis.org/,"[{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...",[{'title': 'The Arabidopsis Information Resour...

In [7]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10')
    col_10 = cursor.fetchall()

rnc2_df = pd.DataFrame(col_10)
rnc2_df.head()

         0         1       2                                   3
0  NONCODE    234669       7             http://www.noncode.org/
1     VEGA         0       0           http://vega.sanger.ac.uk/
2  GENCODE     47677       2            http://gencodegenes.org/
3      ENA  12086180  814855  https://www.ebi.ac.uk/ena/browser/
4     TAIR      4406       1         http://www.arabidopsis.org/